options:
  logging: CLOUD_LOGGING_ONLY

steps:
# 1️⃣ Build Docker image
- name: 'gcr.io/cloud-builders/docker'
  args:
    - build
    - -t
    - asia-south1-docker.pkg.dev/$PROJECT_ID/webapp-repo/my-app:$SHORT_SHA
    - .

# 2️⃣ Push Docker image
- name: 'gcr.io/cloud-builders/docker'
  args:
    - push
    - asia-south1-docker.pkg.dev/$PROJECT_ID/webapp-repo/my-app:$SHORT_SHA

# 3️⃣ Deploy to DEV cluster (fixed sed)
- name: 'gcr.io/cloud-builders/kubectl'
  entrypoint: 'bash'
  args:
    - -c
    - |
      sed "s@\${SHORT_SHA}@$SHORT_SHA@g" deployment-dev.yaml | kubectl apply -f -
  env:
    - CLOUDSDK_COMPUTE_ZONE=asia-south1-a
    - CLOUDSDK_CONTAINER_CLUSTER=dev-cluster
