options:
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _PROJECT_ID: gcp-cicd-pipeline-demo-project

steps:
- name: gcr.io/cloud-builders/docker
  args:
    - build
    - -t
    - asia-south1-docker.pkg.dev/${_PROJECT_ID}/webapp-repo/my-app:$SHORT_SHA
    - .

- name: gcr.io/cloud-builders/docker
  args:
    - push
    - asia-south1-docker.pkg.dev/${_PROJECT_ID}/webapp-repo/my-app:$SHORT_SHA

- name: gcr.io/cloud-builders/gcloud
  args:
    - deploy
    - releases
    - create
    - release-$SHORT_SHA
    - --delivery-pipeline=webapp-pipeline
    - --region=asia-south1
    - --skaffold-file=skaffold.yaml
    - --images=asia-south1-docker.pkg.dev/${_PROJECT_ID}/webapp-repo/my-app:$SHORT_SHA
    - --project=${_PROJECT_ID}
