steps:
  # Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - build
      - -t
      - asia-south1-docker.pkg.dev/$PROJECT_ID/webapp-repo/my-app:$SHORT_SHA
      - .

  # Push Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - push
      - asia-south1-docker.pkg.dev/$PROJECT_ID/webapp-repo/my-app:$SHORT_SHA

  # Deploy to DEV cluster
  - name: 'gcr.io/cloud-builders/kubectl'
    args:
      - apply
      - -f
      - deployment-dev.yaml
    env:
      - CLOUDSDK_COMPUTE_ZONE=asia-south1-a
      - CLOUDSDK_CONTAINER_CLUSTER=dev-cluster
