apiVersion: skaffold/v4
kind: Config
metadata:
  name: webapp
build:
  artifacts:
    - image: asia-south1-docker.pkg.dev/gcp-cicd-pipeline-demo-project/webapp-repo/my-app
deploy:
  kubectl:
    manifests:
      - k8s/deployment.yaml
      - k8s/service.yaml
