apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: dev
gke:
  cluster: projects/gcp-cicd-pipeline-demo-project/locations/asia-south1-a/clusters/dev-cluster
---
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: prod
requireApproval: true
gke:
  cluster: projects/gcp-cicd-pipeline-demo-project/locations/asia-south1-a/clusters/prod-cluster
